config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'pages#index'

  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get ':page_name', controller: :pages,
                    action: :index,
                    constraints: { page_name: /(about|contacts|become_a_tutor|help|howitworks)/ }
  get 'search', action: :index, controller: 'search'

  resource :profile, except: %i[index destroy]
  resource :settings, only: :show

  resources :dashboard
  resource :profile, except: %i[index destroy]
  resources :tutors, only: %i[show]
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  expose :resource, -> { current_user }
end

app/views/settings/_account_settings_form.html.slim
= simple_form_for resource, url: user_registration_path, html: {method: :patch}, remote: true do |f|
  = f.error_notification
  = f.input :email, required: true, autofocus: true
  = f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it", required: false
  = f.input :password_confirmation, required: false
  = f.input :current_password, required: true
  = f.button :submit, "Update"
small
  == "Unhappy? #{link_to "Cancel my account", registration_path(:user), data: {confirm: "Are you sure?"}, method: :delete}"

app/views/settings/show.html.slim
h2= t('.title')
.d-flex.flex-column-reverse.tabs
  #account.tab-content.w-100.p-4.bg-white= render 'account_settings_form'
  #privacy.tab-content.w-100.p-4.bg-white
    h3= t('.privacy_settings')
  #notifications.tab-content.w-100.p-4.bg-white
    h3= t('.notifications_settings')
  ul.nav.nav-tabs.w-100
    li.nav-item= link_to t('.account_settings'), '#account', class: 'nav-link', data: {turbolinks: false}
    li.nav-item= link_to t('.privacy_settings'), '#privacy', class: 'nav-link', data: {turbolinks: false}
    li.nav-item= link_to t('.notifications_settings'), '#notifications', class: 'nav-link', data: {turbolinks: false}