config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'pages#index'

  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get ':page_name', controller: :pages,
                    action: :index,
                    constraints: { page_name: /(about|contacts|become_a_tutor|help|howitworks)/ }
  get 'search', action: :index, controller: 'search'

  resource :profile, except: %i[index destroy]
  resource :settings, only: :show

  resources :dashboard
  resource :profile, except: %i[index destroy]
  resources :tutors, only: %i[show]
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :check_profile_completion

  expose :current_profile, (-> { current_user&.profile })

  private

  def check_profile_completion
    redirect_to new_profile_path unless current_profile&.valid? || devise_controller?
  end

  def authenticate_admin!
    redirect_to new_user_session_path unless current_user&.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.slim
#flash
  - flash.select { |_k, v| v.is_a? String }.each do |type, message|
    div class="alert alert-dismissable bg-#{type == 'alert' ? 'danger' : 'success'}" role="alert"
      button.close aria-hidden="true" data-dismiss="alert" type="button"
        i.fa.fa-times
      = message

app/views/application/_footer.html.slim
nav.navbar.navbar-dark.bg-primary.navbar-expand-lg.fixed-bottom
  .container-fluid
    ul.navbar-nav
      li.nav-item
        = link_to t('.tutor'), '/become_a_tutor', class: 'nav-link'
      li.nav-item
        = link_to t('.help'), '/help', class: 'nav-link'
      li.nav-item
        = link_to t('.about'), '/about', class: 'nav-link'
      li.nav-item
        = link_to t('.contacts'), '/contacts', class: 'nav-link'
      li.nav-item
        = link_to t('.howitworks'), '/howitworks', class: 'nav-link'

app/views/application/_head.html.slim
head
  meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
  meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
  title= t('.title')
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

app/views/application/_header.html.slim
nav.navbar.navbar-dark.bg-primary.navbar-expand-lg.fixed-top
  .container-fluid
    .float-lg-left
      = link_to t('.title'), root_path, class: 'navbar-brand'
    = form_tag search_path, method: :get, id: 'header_search_form', class: 'form-inline' do
      = text_field_tag :search_query, params[:search_query], id: 'header-search-query', class: 'form-control mr-sm-2', placeholder: t('.find_tutor')
      = submit_tag t('.search'), name: nil, class: 'btn btn-outline-success my-2 my-sm-0'
    .float-lg-right
      = render user_signed_in? ? 'user_nav' : 'nav'

app/views/application/_nav.html.slim
ul.navbar-nav
  li.nav-item= link_to t('.login'), new_user_session_path, class: 'nav-link'
  li.nav-item= link_to t('.sign_up'), new_user_registration_path, class: 'nav-link'

app/views/application/_sidebar.html.slim
#sidebar.navbar.navbar-dark.bg-dark.navbar-expand-lg.text-center.flex-column
  ul.nav.w-100
    li.nav-item.w-100
      = link_to dashboard_index_path, class: 'nav-link' do
        = fa_icon 'bar-chart', text: t('.dashboard'), class: 'fa-5x'

app/views/application/_user_nav.html.slim
ul.navbar-nav
  li.nav-item.dropdown
    .d-flex.flex-row.justify-content-center.align-items-center data-toggle="dropdown"
      .dropdown-toggle.m-1
      .thumbnail= cl_image_tag(current_profile.avatar.small) if current_profile
    .dropdown-menu.dropdown-menu-right
      = link_to t('.settings'), settings_path(anchor: :account), class: 'dropdown-item', data: {turbolinks: false}
      = link_to t('.profile'), profile_path, class: 'dropdown-item'
      = link_to t('.profile_edit'), edit_profile_path, class: 'dropdown-item'
      .dropdown-divider
      = link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'dropdown-item'

app/views/application/head.html.slim
head
  meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
  meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
  title Tutor Temple
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags